
# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll


html_title: ahsan's island
title: 
brand_title: ahsan's island
main_short_description: a personal blog/website :D i teach olympiad mathematics sometimes :0 oh, and i love painting, listening to music, and reading manga :D
about_me: >- 
  I'm M Ahsan Al Mahir, a first year Mathematics and Computer Science student at Brag University. I previously participated in the International Mathematical Olympiad in 2019 and 2020. I love learning mathematics, my favorite topics are mathematical analysis and discrete mathematics. I also love teaching others about mathematics. You can check my courses in below.

email: ahsanalmahir@gmail.com

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/:num/"
