
# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll


html_title: Learn With Lazim
title: This is the main title of the website
brand_title: Learn With Lazim
main_short_description: This is the short description under title in the home page
about_me: >- 
  This is the about me section. My name is Ahnaf Shahriar Asif and I suck at every single thing that exists. I am 18, but I'm single, virgin and I fuck my life.

email: ahnafshahriar92@gmail.com

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/:num/"